name: call_system
description: Care Alert - Sistema de chamada assistiva e notificação em tempo real.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.13.6
  
  # Notificações
  flutter_local_notifications: ^17.0.0
  
  # UI
  google_fonts: ^6.1.0
  
  # Utilitários
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.2
  
  # Rede Local (Fase 2 - preparação)
  web_socket_channel: ^2.4.0
  network_info_plus: ^5.0.0
  multicast_dns: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets para sons customizados (fase futura)
  # assets:
  #   - assets/sounds/
